# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-30 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_auto_20180406_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collecteddata',
            name='cumulative_achieved',
        ),
        migrations.RemoveField(
            model_name='historicalcollecteddata',
            name='cumulative_achieved',
        ),
    ]
