# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0025_auto_20180430_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='date_collected',
            field=models.DateField(blank=True, help_text=b' ', null=True, verbose_name='Date collected'),
        ),
        migrations.AlterField(
            model_name='historicalcollecteddata',
            name='date_collected',
            field=models.DateField(blank=True, help_text=b' ', null=True, verbose_name='Date collected'),
        ),
    ]
