# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0026_auto_20180510_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='customsort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Customsort'),
        ),
    ]
