# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-17 14:27
from __future__ import unicode_literals

from django.db import migrations


def gen_customsort(apps, schema_editor):
    level_model = apps.get_model("indicators", "Level")
    levels = level_model.objects.all()
    for l in levels:
        if l.name == 'Goal':
            l.customsort = 1
        elif l.name == 'Impact':
            l.customsort = 2
        elif l.name == 'Outcome':
            l.customsort = 3
        elif l.name == 'Intermediate Outcome':
            l.customsort = 4
        elif l.name == 'Output':
            l.customsort = 5
        elif l.name == 'Activity':
            l.customsort = 6
        l.save()


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0027_level_customsort'),
    ]

    operations = [
        migrations.RunPython(gen_customsort, reverse_code=migrations.RunPython.noop),
    ]
