# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0028_auto_20180517_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'ordering': ('indicator', 'date_collected'), 'verbose_name_plural': 'Indicator Output/Outcome Collected Data'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('customsort',), 'verbose_name': 'Level'},
        ),
        migrations.AlterField(
            model_name='periodictarget',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodictargets', to='indicators.Indicator', verbose_name='Indicator'),
        ),
    ]
