# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0029_auto_20180604_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, 'Direction of change (not applicable)'), (2, 'Increase (+)'), (3, 'Decrease (-)')], default=1, help_text=b' ', null=True, verbose_name='Direction of Change'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='direction_of_change',
            field=models.IntegerField(choices=[(1, 'Direction of change (not applicable)'), (2, 'Increase (+)'), (3, 'Decrease (-)')], default=1, help_text=b' ', null=True, verbose_name='Direction of Change'),
        ),
    ]
