# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0030_auto_20180613_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.TolaTable', verbose_name='TolaTable'),
        ),
    ]
