# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-06 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0031_auto_20180615_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ('program', 'name'), 'verbose_name': 'Program Objective'},
        ),
        migrations.AlterModelOptions(
            name='strategicobjective',
            options={'ordering': ('country', 'name'), 'verbose_name': 'Country Strategic Objectives'},
        ),
    ]
