# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0021_auto_20181026_1449'),
        ('indicators', '0032_auto_20180706_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTTIndicator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('indicators.indicator',),
            managers=[
                ('notargets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramWithMetrics',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('workflow.program',),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_agreement2', to='workflow.ProjectAgreement', verbose_name='Project Initiation'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_data', to='workflow.TolaUser', verbose_name='Originated By'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='evidence',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Documentation', verbose_name='Evidence Document or Link'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='periodic_target',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.PeriodicTarget', verbose_name='Periodic target'),
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='tola_table',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.TolaTable', verbose_name='TolaTable'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='external_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExternalService', verbose_name='External service'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approval_submitted_by',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_submitted_by', to='workflow.TolaUser', verbose_name='Approval submitted by'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_indicator', to='workflow.TolaUser', verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='data_collection_frequency',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.DataCollectionFrequency', verbose_name='Frequency of Data Collection'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='external_service_record',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExternalServiceRecord', verbose_name='External Service ID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingFrequency', verbose_name='Frequency of Reporting'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, help_text=b' ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Sector', verbose_name='Sector'),
        ),
    ]
