# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-06 07:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20180918_1554'),
        ('indicators', '0033_pinnedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTTIndicator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('indicators.indicator',),
            managers=[
                ('notargets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramWithMetrics',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('workflow.program',),
            managers=[
                ('with_metrics', django.db.models.manager.Manager()),
            ],
        ),
    ]
