# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def set_temp_program_id(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    for indicator in Indicator.objects.all():
        if indicator.program.all().count() == 0:
            program_id = None
        else:
            program_id = indicator.program.all().first().id
        indicator.program_temp = program_id
        indicator.save()

def move_temp_program_id(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    for indicator in Indicator.objects.all():
        indicator.program_id = indicator.program_temp
        indicator.save()

def test_program_id_uniqueness(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    for indicator in Indicator.objects.all():
        if indicator.program.all().count() > 1:
            raise Exception('Indicator {0} has more than 1 program, fix then rerun'.format(indicator.id))

class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_auto_20180918_1554'),
        ('indicators', '0034_ipttindicator_programwithmetrics'),
    ]
    operations = [
        migrations.RunPython(test_program_id_uniqueness),
        migrations.AddField(
            model_name='historicalindicator',
            name='program',
            field=models.ForeignKey(
                blank=True, db_constraint=False, null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+', to='workflow.Program'),
        ),
        # first add a temp field to hold the foreign key
        migrations.AddField(
            model_name='indicator',
            name='program_temp',
            field=models.IntegerField(
                null=True, blank=True, help_text=b'Program Temp',
                verbose_name='Program Temp'),
            preserve_default=False,
        ),
        # put the value of the program the indicator is assigned to there
        migrations.RunPython(set_temp_program_id),
        migrations.RemoveField(
            model_name='indicator',
            name='program',
        ),
        # add the real foreign key
        migrations.AddField(
            model_name='indicator',
            name='program',
            field=models.ForeignKey(
                null=True, blank=True, help_text=b'Program',
                on_delete=django.db.models.deletion.CASCADE,
                to='workflow.Program', verbose_name='Program'),
            preserve_default=False,
        ),
        # copy the temp key over
        migrations.RunPython(move_temp_program_id),
        migrations.RemoveField(
            model_name='indicator',
            name='program_temp',
        ),
    ]
