# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-09 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0033_auto_20181026_1449'),
        ('indicators', '0036_make_level_indicator_foreignkey'),
    ]

    operations = [
    ]
