# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0038_auto_20181112_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsIndicator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('indicators.indicator',),
        ),
    ]
