# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models
from indicators.management.commands.convert_lop_to_numeric import run_conversion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0040_add_index_for_collecteddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindicator',
            name='approval_submitted_by',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='data_collection_frequency',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='external_service_record',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='level',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='reporting_frequency',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='sector',
        ),
        migrations.DeleteModel(
            name='HistoricalIndicator',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='lop_target',
            new_name='lop_target_old',
        ),
        migrations.AddField(
            model_name='indicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True,
                                      verbose_name='Life of Program (LoP) target*'),
        ),
        migrations.RunPython(run_conversion),
        migrations.RemoveField(
            model_name='indicator',
            name='lop_target_old',
        ),
    ]
