# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models
from indicators.management.commands.convert_lop_to_numeric import run_conversion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0040_add_index_for_collecteddata'),
    ]

    operations = [
        migrations.RunPython(run_conversion),
        migrations.AlterField(
            model_name='historicalindicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True, verbose_name='Life of Program (LoP) target*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True, verbose_name='Life of Program (LoP) target*'),
        ),
    ]
