# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0041_auto_20181206_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorHistory',
            fields=[
                ('lop_target', models.CharField(max_length=255)),
                ('rationale_for_target', models.TextField()),
                ('history_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indicators_historicalindicator',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='approval_submitted_by',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='data_collection_frequency',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='external_service_record',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='level',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='program',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='reporting_frequency',
        ),
        migrations.RemoveField(
            model_name='historicalindicator',
            name='sector',
        ),
        migrations.DeleteModel(
            name='HistoricalIndicator',
        ),
    ]
