# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-19 00:05
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0041_lop_to_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictarget',
            name='target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Target'),
        ),
    ]
