# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0042_auto_20181206_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='lop_target_old',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True, verbose_name='Life of Program (LoP) target*'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.TextField(blank=True, help_text=b' ', max_length=60, null=True, verbose_name='Life of Program (LoP) target*'),
        ),
    ]
