# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-27 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0042_validate_ptarget_gt_zero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='baseline',
            field=models.CharField(blank=True, help_text=b' ', max_length=255, null=True, verbose_name='Baseline'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='lop_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b' ', max_digits=20, null=True, verbose_name=b'Life of Program (LoP) target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text=b' ', max_length=135, null=True, verbose_name='Unit of measure'),
        ),
    ]
