# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-19 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0042_collecteddata_to_result_rename'),
        ('indicators', '0042_validate_ptarget_gt_zero'),
    ]

    operations = [
    ]
