# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-28 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0043_indicator_setup_remove_asterisks'),
        ('indicators', '0043_merge_20181219_1137'),
    ]

    operations = [
    ]
