# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-15 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0044_merge_20181228_1340'),
        ('indicators', '0045_resultstarget_proxy_model'),
    ]

    operations = [
    ]
