# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-19 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0047_evidence_field_and_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalresult',
            old_name='evidence_name',
            new_name='record_name',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='evidence_name',
            new_name='record_name',
        ),
        migrations.RemoveField(
            model_name='historicalresult',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='result',
            name='comment',
        ),
    ]
