# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-07 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0047_evidence_field_and_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
