# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-19 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0048_auto_20190118_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresult',
            name='description',
            field=models.TextField(blank=True, default=b'', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=models.TextField(blank=True, default=b'', verbose_name='Comments'),
        ),
        migrations.RenameField(
            model_name='historicalresult',
            old_name='description',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='description',
            new_name='comments',
        ),
    ]
