# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-21 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0049_auto_20190118_1703'),
        ('workflow', '0024_remove_qmark_from_verbose_name'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE indicators_pinnedreport CONVERT TO CHARACTER SET utf8'),
        migrations.RunSQL('ALTER TABLE workflow_formguidance CONVERT TO CHARACTER SET utf8'),
    ]
