# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-22 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0050_fix_encoding_on_tables'),
        ('indicators', '0048_indicator_deleted'),
    ]

    operations = [
    ]
