# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-08 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.forms.models import model_to_dict


def move_old_data(apps, schema_editor):
    Indicator = apps.get_model('indicators', 'Indicator')
    Level = apps.get_model('indicators', 'Level')
    for indicator in Indicator.objects.all():
        try:
            indicator.old_level = indicator.level.name
        except AttributeError:
            indicator.old_level = None
        indicator.level = None
        indicator.save()

    for level in Level.objects.all():
        level.delete()


def reverse_migration(apps, schema_editor):
    """Allow the reverse migration to happen"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_remove_qmark_from_verbose_name'),
        ('indicators', '0050_fix_encoding_on_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=135, verbose_name='Name')),
                ('tier_depth', models.IntegerField(verbose_name='Level Tier depth')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create date')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='Edit date')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_tiers',
                                              to='workflow.Program')),
            ],
            options={
                'ordering': ('tier_depth',),
                'verbose_name': 'Level Tier',
            },
        ),

        migrations.AddField(
            model_name='indicator',
            name='old_level',
            field=models.CharField(blank=True, help_text=b' ', max_length=80, null=True, verbose_name='Old Level'),
        ),

        migrations.RunPython(move_old_data, reverse_migration),

        migrations.AddField(
            model_name='level',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_levels', to='indicators.Level'),
        ),
        migrations.AddField(
            model_name='level',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='workflow.Program'),
        ),
        migrations.AlterField(
            model_name='level',
            name='customsort',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sort Order'),
        ),
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set([('parent', 'customsort')]),
        ),
        migrations.AlterUniqueTogether(
            name='leveltier',
            unique_together=set([('program', 'tier_depth'), ('name', 'program')]),
        ),
    ]
