# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-09 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0052_strategicobjective_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicobjective',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='status'),
        ),
    ]
