# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-16 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0053_strategicobjective_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='target_frequency_custom',
            field=models.CharField(blank=True, help_text=b' ', max_length=100, null=True, verbose_name='First event name'),
        ),
    ]
