# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0054_auto_20190415_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicobjective',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status'),
        ),
    ]
