# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0055_auto_20190425_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalservice',
            name='feed_url',
            field=models.CharField(blank=True, max_length=765, verbose_name='Feed URL'),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='url',
            field=models.CharField(blank=True, max_length=765, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='externalservicerecord',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Evidence URL'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='record_name',
            field=models.CharField(blank=True, max_length=135, verbose_name='Record name'),
        ),
        migrations.AlterField(
            model_name='result',
            name='create_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='result',
            name='edit_date',
            field=models.DateTimeField(blank=True, help_text=b' ', null=True, verbose_name='Edit date'),
        ),
        migrations.AlterField(
            model_name='result',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Evidence URL'),
        ),
        migrations.AlterField(
            model_name='result',
            name='record_name',
            field=models.CharField(blank=True, max_length=135, verbose_name='Record name'),
        ),
        migrations.AlterField(
            model_name='result',
            name='site',
            field=models.ManyToManyField(blank=True, help_text=b' ', to='workflow.SiteProfile', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='tolatable',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
