# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0055_auto_20190425_1030'),
        ('indicators', '0052_add_level_assumptions'),
    ]

    operations = [
    ]
