# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0056_merge_20190429_0955'),
        ('indicators', '0056_add_verbose_names_to_indicator_fields'),
    ]

    operations = [
    ]
