# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-01 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0053_indicator_level_order'),
        ('indicators', '0056_merge_20190429_0955'),
    ]

    operations = [
    ]
