# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-29 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0057_merge_20190501_1450'),
        ('indicators', '0057_merge_20190506_0917'),
    ]

    operations = [
    ]
