# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0058_merge_20190529_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name'),
        ),
    ]
