# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0060_ind_level_fields_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together=set([('level', 'level_order', 'deleted')]),
        ),
    ]
