# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-15 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0061_auto_20190614_1201'),
        ('indicators', '0061_add_deleted_to_levelorder_uniqueness'),
    ]

    operations = [
    ]
