# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0063_sentence_case_level_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='assumptions',
            field=models.TextField(blank=True, default='', verbose_name='Assumptions'),
            preserve_default=False,
        ),
    ]
