# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-13 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0065_longer_indicator_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresult',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Evidence URL'),
        ),
        migrations.AlterField(
            model_name='historicalresult',
            name='record_name',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Record name'),
        ),
        migrations.AlterField(
            model_name='result',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Evidence URL'),
        ),
        migrations.AlterField(
            model_name='result',
            name='record_name',
            field=models.CharField(blank=True, max_length=135, null=True, verbose_name='Record name'),
        ),
    ]
