# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-01 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0066_add_LevelTierTemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltiertemplate',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Template name'),
        ),
    ]
