# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0068_templates_use_list_field'),
        ('indicators', '0066_auto_20190813_1244'),
    ]

    operations = [
    ]
