# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('indicators', '0042_collecteddata_to_result_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='collected',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=models.deletion.CASCADE, to='indicators.Result'),
        ),
    ]
