describe('Collected data datepicker with typed-in dates ', {
    it('does not display a date automatically when selected', {})
    it('closes the datpicker window after selecting a date', {})
    it('assigns given value to correct period if program liftime includes date (annual)', {})
    it('assigns given value to correct period if program liftime includes date (semiannual)', {})
    it('assigns given value to correct period if program liftime includes date (triannual)', {})
    it('assigns given value to correct period if program liftime includes date (quarterly)', {})
    it('assigns given value to correct period if program liftime includes date (monthly)', {})
    it('displays warning message if given date is outside program lifetime', {})
    it('does not do the hokey-pokey', {})
})

describe('Collected data datepacker with clicked dates', {
    it('does not display a date automatically when selected', {})
    it('closes the datpicker window after selecting a date', {})
    it('assigns given value to correct period if program liftime includes date (annual)', {})
    it('assigns given value to correct period if program liftime includes date (semiannual)', {})
    it('assigns given value to correct period if program liftime includes date (triannual)', {})
    it('assigns given value to correct period if program liftime includes date (quarterly)', {})
    it('assigns given value to correct period if program liftime includes date (monthly)', {})
    it('displays warning message if given date is outside program lifetime', {})
    it('does not do the hokey-pokey', {})
})
