# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-03 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jupyternotebooks',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programlinks',
            name='link',
        ),
        migrations.RemoveField(
            model_name='programlinks',
            name='program',
        ),
        migrations.RemoveField(
            model_name='programnarratives',
            name='program',
        ),
        migrations.DeleteModel(
            name='JupyterNotebooks',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='ProgramLinks',
        ),
        migrations.DeleteModel(
            name='ProgramNarratives',
        ),
    ]
