# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20180514_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolauser',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'fr', 'French'), (b'es', 'Spanish'), (b'ar', 'Arabic')], default='en', max_length=2),
        ),
    ]
