# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-18 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_language_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarks',
            name='percent_complete',
            field=models.IntegerField(blank=True, null=True, verbose_name='%% complete'),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='percent_cumulative',
            field=models.IntegerField(blank=True, null=True, verbose_name='%% cumulative completion'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='language',
            field=models.CharField(choices=[(b'en', 'English'), (b'fr', 'French'), (b'es', 'Spanish')], default='en', max_length=2),
        ),
    ]
