# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0023_tolauser_activecountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolauser',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='users', to='workflow.Country', verbose_name='Accessible Countries'),
        ),
    ]
