# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-16 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0024_remove_qmark_from_verbose_name'),
        ('workflow', '0024_auto_20181220_0923'),
    ]

    operations = [
    ]
