# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-16 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0025_merge_20190116_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolauser',
            name='mode_of_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tolauser',
            name='mode_of_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tolauser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='user_access',
            field=models.ManyToManyField(blank=True, related_name='program_access', to='workflow.TolaUser'),
        ),
    ]
