# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-21 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_auto_20190120_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
