# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-24 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_organization_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolausercountryroles',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('basic_admin', 'Basic Admin')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tolausercountryroles',
            unique_together=set([('country', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='tolauserprogramroles',
            unique_together=set([('program', 'user')]),
        ),
    ]
