# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_auto_20190127_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolauser',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
