# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_auto_20190227_1023'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ProgramAccess',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                    options={
                        'db_table': 'workflow_program_user_access',
                    },
                ),
                migrations.AlterField(
                    model_name='program',
                    name='user_access',
                    field=models.ManyToManyField(blank=True, related_name='program_access', through='workflow.ProgramAccess', to='workflow.TolaUser'),
                ),
                migrations.AddField(
                    model_name='programaccess',
                    name='program',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Program'),
                ),
                migrations.AddField(
                    model_name='programaccess',
                    name='tolauser',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.TolaUser'),
                ),
                migrations.AlterUniqueTogether(
                    name='programaccess',
                    unique_together=set([('program', 'tolauser')]),
                ),
            ],
            database_operations=[]
        )
    ]
