# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0033_auto_20190227_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='gaitid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID'),
        ),
    ]
