# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0036_auto_20190301_1110'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CountryAccess',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Country')),
                    ],
                    options={
                        'db_table': 'workflow_tolauser_countries',
                    },
                ),
                migrations.AlterField(
                    model_name='tolauser',
                    name='countries',
                    field=models.ManyToManyField(blank=True, related_name='users', through='workflow.CountryAccess', to='workflow.Country', verbose_name='Accessible Countries'),
                ),
                migrations.AddField(
                    model_name='countryaccess',
                    name='tolauser',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.TolaUser'),
                ),
                migrations.AlterUniqueTogether(
                    name='countryaccess',
                    unique_together=set([('tolauser', 'country')]),
                ),
            ],
            database_operations=[]
        )
    ]
