# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-01 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_auto_20190301_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryaccess',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('basic_admin', 'Basic Admin')], default='user', max_length=100),
        ),
    ]
