# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-01 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0038_countryaccess_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tolausercountryroles',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tolausercountryroles',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tolausercountryroles',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tolauserprogramroles',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tolauserprogramroles',
            name='program',
        ),
        migrations.RemoveField(
            model_name='tolauserprogramroles',
            name='user',
        ),
        migrations.DeleteModel(
            name='TolaUserCountryRoles',
        ),
        migrations.DeleteModel(
            name='TolaUserProgramRoles',
        ),
    ]
