# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-05 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_auto_20190301_1206'),
        ('workflow', '0034_nullable_gaitid_20190304_1242'),
    ]

    operations = [
    ]
