# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-02 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_auto_20190228_1453'),
        ('workflow', '0040_merge_20190305_1220'),
    ]

    operations = [
    ]
