# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_merge_20190402_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='gaitid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID'),
        ),
    ]
