# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0043_explicate_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolauser',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='tolauser',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Organization', verbose_name='Organization'),
        ),
    ]
