# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


def fill_username(apps, schema_editor):
    TolaUser = apps.get_model('workflow', 'TolaUser')
    for tola_user in TolaUser.objects.filter(name=' ').select_related('user'):
        auth_user = tola_user.user
        tola_user.name = "%s %s" % (auth_user.first_name, auth_user.last_name)
        tola_user.save()


def reverse_migration(apps, schema_editor):
    """Allow the reverse migration to happen"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0045_auto_20190425_1109'),
    ]

    operations = [
        migrations.RunPython(fill_username, reverse_code=reverse_migration),
    ]
