# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-15 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0047_add_program_using_results_framework_booleanfield'),
        ('workflow', '0047_add_home_country_to_countryaccess'),
    ]

    operations = [
    ]
