# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0048_merge_20190515_1658'),
    ]

    operations = [
        # first add the field with a default of false, so existing programs are set as "unmigrated"
        migrations.AddField(
            model_name='program',
            name='auto_number_indicators',
            field=models.BooleanField(default=False, verbose_name='Auto-number indicators according to the results framework'),
        ),
        # now make the default true so all new programs going forward have this set
        # (new programs don't need migration time)
        migrations.AlterField(
            model_name='program',
            name='auto_number_indicators',
            field=models.BooleanField(default=True, verbose_name='Auto-number indicators according to the results framework'),
        )
    ]
