# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-12 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tola_management', '0003_auto_20190207_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programauditlog',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indicators.Indicator'),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='new_entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programauditlog',
            name='previous_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
