# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-12 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tola_management', '0004_auto_20190212_0956'),
        ('tola_management', '0003_programadminauditlog'),
    ]

    operations = [
    ]
