# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-08 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tola_management', '0006_organizationadminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programauditlog',
            name='rationale',
            field=models.TextField(null=True),
        ),
    ]
